### ISSUE TITLE
Add named exports

### ISSUE THREAD

**Issue by albertogasparin** [rprieto/mocha-steps#11]
Would it be nice if we can get `step` (and other methods as well) as named export?
So we can require/import them without the need of specifying a global variable:

```js
var step = require('mocha-steps').step;
var xstep = require('mocha-steps').xstep;

// even better with es modules
import { step, xstep } from 'mocha-steps';
```

**Comment by albertogasparin** [comment]
My pleasure. Just a note: whenever you are going to release a new version would you mind updating the version number in `package.json`? It still says `version": "0.0.1"`.
Thanks

**Comment by rprieto** [comment]
My bad, I had that commit locally but never pushed it. Version `1.0.2` is now on npm as well.
