### ISSUE TITLE
Clarify whether this project causes sequential execution

### ISSUE THREAD

**Issue by monkpit** [rprieto/mocha-steps#14]
It's not exactly clear from the readme whether `mocha-steps` will cause asynchronous tests to execute in sequence.

```
describe('A test suite', function () {
  it('logs in', function() {...});
  it('does a thing, guaranteed to happen after it logs in', function() {...});
});
```

The readme says that if any test fails, the suite will be aborted. The readme does NOT say that the second test is guaranteed to only run after the first one is complete. However, the tagline is "Sequential scenarios for mocha" - sequential suggests that the order of execution is guaranteed.

Could you clarify on what you mean by "sequential"?

**Comment by rprieto** [comment]
Hi,

My understanding is that Mocha tests are always sequential. In your example, the second `it` always executes after the first one, even without `mocha-steps`.

What mocha-steps adds is ensuring that the second `it` doesn't run if the first one failed.

**Comment by monkpit** [comment]
However, if the first test returned a promise and immediately processed the second test, while the first was asynchronously running, what is the outcome? Is the first test _guaranteed_ to finish before the test second begins?

**Comment by monkpit** [comment]
So the answer is YES, this is how mocha works behind the scenes, both out-of-the-box and also with the mocha-as-promised extension.

Which is really cool!

So, by extension, `mocha-steps` should also have the same functionality.


Thanks for supporting a cool project and dealing with my questions!

**Comment by rprieto** [comment]
That's right, even if you return a promise, mocha will wait for it to resolve to pass/fail the test, before moving on to the next one. This behaviour stays the same with `mocha-steps`.

Happy to help!

**Comment by rprieto** [comment]
I forgot to mention: you should need `mocha-as-promised` anymore since Mocha now supports promises out of the box.
