### ISSUE TITLE
Does not work with this.retries(n)

### ISSUE THREAD

**Issue by z-vr** [rprieto/mocha-steps#15]
Does not work with [retries](https://mochajs.org/#retry-tests)

**Comment by albertogasparin** [comment]
I'm also supporting this request. Currently if your test describe has `retries(n)` and fails just the first time, `mocha-steps` will mark all subsequent steps as to skip even if the failing test succeeded on retry. Given this code:

```js
describe('my test', function () {
  this.retries(1);
  var run;
  step('should fail first time', function() {
    var isRun = Boolean(run);
    run = true;
    expect(isRun).to.eql(true);
  });
  step('should pass', function() {
    expect('').to.eql('');
  });
});
```

The current output is: 

```
1 passing
1 skipped
```

Which is quite cryptic as no error is reported (correct behaviour from mocha). Supporting `retries(n)` would help people like us using `step` on integration/E2E tests where we have to deal with flaky tests.

**Comment by albertogasparin** [comment]
@rprieto, as #16 has be merged would you kindly release a new version on npm and close this issue? 😊

**Comment by rprieto** [comment]
Version `1.1.0` is out, let me know if it works!
