### ISSUE TITLE
Subsequent steps are not skipped if a test times out

### ISSUE THREAD

**Issue by nmuth** [rprieto/mocha-steps#17]
The following test:

```
describe.only('timeout bug', function() {
  this.timeout(1000)

  step('times out', () => new Promise(resolve => setTimeout(resolve, 10000)))

  step('should be skipped', () => {
    expect(1 + 1).to.equal(2)
  })
})
```

Results in the following output:

```
$ mocha -r ts-node/register test/e2e/**/*.ts test/e2e/*.ts
loading config from config.json


  timeout bug
    1) times out
    ✓ should be skipped


  1 passing (1s)
  1 failing

  1) timeout bug times out:
     Error: Timeout of 1000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

When the first test times out, `mocha-steps` should skip the second test. Do you have time to look at this? I might be able to put together a patch but I've never written a mocha plugin before 😄

**Comment by ojizero** [comment]
What seems odd to me is that in the test case [return_it](https://github.com/rprieto/mocha-steps/blob/160c622501feee25792d7ba829b8d2c922676751/test/return_it.js) seems to imply that this is an intended behaviour (given what I understood for it's [expected value](https://github.com/rprieto/mocha-steps/blob/160c622501feee25792d7ba829b8d2c922676751/test/return_it.txt) that is) ¯\\_(ツ)_/¯ 

But this does seem like an odd behaviour, given that a timed out test is effectively the same as a failed test 🤔 

@rprieto any ideas if this is intended or is an incorrect behaviour?

**Comment by rprieto** [comment]
Hi, it does look like a bug! I'll try to look at it but don't hesitate to give it a try and submit a PR too.

**Comment by ojizero** [comment]
@rprieto heyy, I just opened a PR attemp at fixing this issue, if you have time please check it ^_^
