### ISSUE TITLE
Usage of xstep - difference with step

### ISSUE THREAD

**Issue by Metachemix1** [rprieto/mocha-steps#23]
In the example in the readme file 2 types of test steps are being used.

Step and xstep.. What is the difference between those two? Is xstep some "final" step or something perhaps?

Awaiting an answer.

Kind regards

**Comment by ojizero** [comment]
Not the author here, but it seems to be the same as Mocha's function `xit`, basically allows skipping a test case.

In Mocha a test case can also be skipped using `it.skip` which unfortunately doesn't seem to be the case here (`step.skip` doesn't work so to skip a test case you can only use `xstep`)

**Comment by rprieto** [comment]
That's exactly it, thanks @ojizero
