### ISSUE TITLE
Does not work with returning a Promise

### ISSUE THREAD

**Issue by awlayton** [rprieto/mocha-steps#5]
When a Promise is returned in the function given to a `step`, the test immediately passes without waiting for the Promise to resolve.

**Comment by rprieto** [comment]
Thanks for the bug report! I don't have [test cases](https://github.com/rprieto/mocha-steps/blob/master/test/step.js) for Promises yet, so I'll add some and see if there's a way to handle that.

**Comment by rprieto** [comment]
This should be fixed by #6!
